# Generated by Django 2.2.4 on 2019-11-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ssn',
            field=models.CharField(default='', max_length=100),
        ),
    ]
