# Generated by Django 2.2.4 on 2019-11-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='inarrival',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='indeparture',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='outarrival',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='outdeparture',
            field=models.DateTimeField(),
        ),
    ]
