# Generated by Django 2.2.4 on 2019-11-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='currency',
            field=models.CharField(default='won', max_length=10),
        ),
    ]
