# Generated by Django 2.2.4 on 2019-11-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_ssn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='acounts',
            new_name='account',
        ),
        migrations.AddField(
            model_name='balance',
            name='end_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='balance',
            name='start_date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
