# Generated by Django 2.2.4 on 2019-11-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191122_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='interest',
            field=models.FloatField(default=0.0),
        ),
    ]
