# Generated by Django 2.2.4 on 2019-11-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191123_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='city_id',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='post',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
    ]
