# Generated by Django 2.2.4 on 2019-11-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_balance_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
