# Generated by Django 2.2.4 on 2019-11-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_calendar_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
