# Generated by Django 2.2.4 on 2019-11-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191123_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='currency',
            field=models.CharField(default='dollar', max_length=10),
        ),
    ]
