# Generated by Django 2.2.4 on 2019-11-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_calendar_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='currency',
            field=models.CharField(default='won', max_length=10),
        ),
    ]
